### ISSUE TITLE
View-only variable - does not exist in the class declaration

### ISSUE THREAD

**Issue by k-schneider** [mgechev/codelyzer#189]
I'm using the default settings from angular-cli and this markup is causing a lint error:

```
<div class="input-group">
  <input class="form-control" id="exampleDatePicker" name="dp" placeholder="yyyy-mm-dd" [(ngModel)]="dateVal" ngbDatepicker #d="ngbDatepicker">
  <button type="button" class="btn btn-secondary" (click)="d.toggle()">Toggle Datepicker</button>
</div>
```

The output is:

`The method "d" that you're trying to access does not exist in the class declaration.`

What can I do here if I don't actually want to declare 'd' in my component?

**Comment by mgechev** [comment]
What do you mean by "View-only variable"? Why is it fine to not have this variable declared?

You can disable the rule by using:

```
/* tslint:disable:no-access-missing-member*/
```

**Comment by jessesanders** [comment]
@mgechev - This is still an issue.  If you look closer at his html he is declaring an view only variable, using:

`#d="ngbDatepicker"`

This is a valid way of creating a view variable which then can be used to call the toggle method on the datePicker component.  This is the syntax provided by the angular/bootstrap team.

Turning off the rule means I no longer get to enforce the bad missing member variables just to get past this valid syntax

**Comment by mgechev** [comment]
This is fixed in codelyzer@3.0.0-beta.1. Once codelyzer@3 gets stable enough I will release it out of beta.

**Comment by digimezzo** [comment]
I've just updated codelyzer from version 2.4.0 to 3.0.1 my Angular2 project because I'm experiencing this issue. However I'm still getting the output when using version 3.0.1:

`The method "d" that you're trying to access does not exist in the class declaration.`

Do I need to perform specific steps or configuration to apply this fix?

**Comment by mgechev** [comment]
Take a look at the advanced options of codelyzer. It performs analysis **per file** which means that it's not aware of template references declared in other files. There's experimental support for type checking which performs "deep analysis" (per project). I need to figure out if the slower linting is worth it.

**Comment by pgrm** [comment]
I have this issue again in 3.1 (up to 3.0.1 it worked fine). This is the html:

````
<div class="form-group start-date">
    <input
    class="form-control start-date-input"
    i18n-placeholder placeholder="Select start Date"
    formControlName="start"
    (ngModelChange)="onSelectstartDate($event)"
    ngbDatepicker #startDatePicker="ngbDatepicker"
    [displayMonths]="2"
    [navigation]="false"
    [minDate]="startMinDate"
    [maxDate]="startMaxDate"
    (click)="startDatePicker.toggle()"
    (click)="endDatePicker.close()"
    [ngClass]="{'form-control-danger': isFormControlInvalid(searchForm.controls.start)}">
</div>

<div class="form-group end-date">
    <input
    class="form-control end-date-input"
    i18n-placeholder placeholder="Select end Date"
    formControlName="end"
    (ngModelChange)="onSelectendDate($event)"
    ngbDatepicker #endDatePicker="ngbDatepicker"
    [displayMonths]="2"
    [navigation]="false"
    [minDate]="endMinDate"
    (click)="endDatePicker.toggle()"
    (click)="startDatePicker.close()"
    [ngClass]="{'form-control-danger': isFormControlInvalid(searchForm.controls.end)}">
</div>
````

and these are the errors I see:

````
ERROR: .../file.html[24, 17]: The method "startDatePicker" that you're trying to access does not exist in the class declaration.
ERROR: .../file.html[25, 17]: The method "endDatePicker" that you're trying to access does not exist in the class declaration.
ERROR: .../file.html[40, 17]: The method "endDatePicker" that you're trying to access does not exist in the class declaration.
ERROR: .../file.html[41, 17]: The method "startDatePicker" that you're trying to access does not exist in the class declaration.
````

I don't think this is an actual issue in the html, is it the same bug in codelyzer again?

**Comment by wKoza** [comment]
Did you not have a .codelyser.js config file before like this ?
```javascript
module.exports = {
predefinedDirectives: [
  { selector: 'input', exportAs: 'ngbDatepicker' }
]
};
```

**Comment by pgrm** [comment]
definitely no file containing *codelyser* or *codelyzer* in my repository, but will try it tomorrow, thx

**Comment by mgechev** [comment]
In 3.0.1 the template linting didn't work in the past a couple of days because of changes in the Angular API.

Take a look at the advanced configuration of codelyzer, to add template references manually, or disable these rules. Angular Compiler takes care of this anyway, and you can use it with the language service.
