### ISSUE TITLE
Cannot read property 'split' of undefined with beta 0

### ISSUE THREAD

**Issue by zoehneto** [mgechev/codelyzer#99]
In a project without any linting issues I get the following error since updating to beta 0:
```
ERROR in ./src/app/components/responsive-menu/responsive-menu.component.ts
Module build failed: TypeError: Cannot read property 'split' of undefined
    at RecursiveAngularExpressionVisitor.visitInterpolation (/home/zoehneto/IdeaProjects/tumblr-reader/node_modules/codelyzer/angular/recursiveAngularExpressionVisitor.js:45:35)
    at Interpolation.visit (/home/zoehneto/IdeaProjects/tumblr-reader/node_modules/@angular/compiler/bundles/compiler.umd.js:3260:26)
    at ASTWithSource.visit (/home/zoehneto/IdeaProjects/tumblr-reader/node_modules/@angular/compiler/bundles/compiler.umd.js:3342:27)
    at RecursiveAngularExpressionVisitor.visit (/home/zoehneto/IdeaProjects/tumblr-reader/node_modules/codelyzer/angular/recursiveAngularExpressionVisitor.js:16:13)
    at InputMetadataWalker.Ng2Walker.visitNg2TemplateAST (/home/zoehneto/IdeaProjects/tumblr-reader/node_modules/codelyzer/angular/ng2Walker.js:125:25)
    at InputMetadataWalker.Ng2Walker.visitNg2TemplateBoundElementPropertyAst (/home/zoehneto/IdeaProjects/tumblr-reader/node_modules/codelyzer/angular/ng2Walker.js:136:14)
    at /home/zoehneto/IdeaProjects/tumblr-reader/node_modules/codelyzer/angular/ng2Walker.js:143:60
    at Array.forEach (native)
    at InputMetadataWalker.Ng2Walker.visitNg2TemplateElement (/home/zoehneto/IdeaProjects/tumblr-reader/node_modules/codelyzer/angular/ng2Walker.js:143:24)
    at InputMetadataWalker.Ng2Walker.visitNg2Template (/home/zoehneto/IdeaProjects/tumblr-reader/node_modules/codelyzer/angular/ng2Walker.js:158:25)
    at /home/zoehneto/IdeaProjects/tumblr-reader/node_modules/codelyzer/angular/ng2Walker.js:174:30
    at Array.forEach (native)
    at InputMetadataWalker.Ng2Walker.visitNg2TemplateHelper (/home/zoehneto/IdeaProjects/tumblr-reader/node_modules/codelyzer/angular/ng2Walker.js:173:19)
    at InputMetadataWalker.Ng2Walker.visitClassDecorator (/home/zoehneto/IdeaProjects/tumblr-reader/node_modules/codelyzer/angular/ng2Walker.js:115:22)
    at Array.forEach (native)
    at InputMetadataWalker.Ng2Walker.visitClassDeclaration (/home/zoehneto/IdeaProjects/tumblr-reader/node_modules/codelyzer/angular/ng2Walker.js:72:40)
 @ ./src/app/app.module.ts 47:0-97
 @ ./src/main.ts
 @ multi app
```

The respective component looks like this:
```
import { Component, OnInit, Output, EventEmitter } from '@angular/core';

@Component({
    selector: 'responsive-menu',
    template: `
        <div class="pure-visible-sm menu-bar center" (click)="toggleMenu()">
            <p>Menu</p>
        </div>
        <div class="pure-visible-sm spacer"></div>
        <side-bar (click)="toggleMenu()" class="{{showMenu ? '' : 'pure-hidden-sm'}}"></side-bar>
    `,
    styleUrls: ['./responsive-menu.component.scss']
})
export class ResponsiveMenuComponent implements OnInit {
    @Output() onMenuToggled = new EventEmitter<boolean>();
    showMenu: boolean;

    ngOnInit() {
        this.showMenu = true;
        this.onMenuToggled.emit(this.showMenu);
    }

    toggleMenu() {
        this.showMenu = !this.showMenu;
        this.onMenuToggled.emit(this.showMenu);
    }
}
```

**Comment by mgechev** [comment]
Thanks for the issue. I'll take a look at it and fix I as soon as I can.

**Comment by vikashkumar29** [comment]
Hi  @mgechev,

I am also using the codelyser beta.0 and facing the same issue with the interpolation. I just checked this pull request #101 and meanwhile integrated the changes in the required file as per the pull request.

After integrating the changes, I was able pass though this issue, however later on I started getting exception on : 

```
e:\GitRepo\angular2-seed\node_modules\codelyzer\angular\recursiveAngularExpressionVisitor.js:77
        ast.expression.visit(this);
                       ^
TypeError: ast.expression.visit is not a function
    at RecursiveAngularExpressionVisitor.visitPrefixNot (e:\GitRepo\angular2-seed\node_modules\codelyzer\angular\recursiveAngularExpressionVisitor.js:77:24)
    at PrefixNot.visit (e:\GitRepo\angular2-seed\node_modules\@angular\compiler\bundles\compiler.umd.js:3286:26)
    at ASTWithSource.visit (e:\GitRepo\angular2-seed\node_modules\@angular\compiler\bundles\compiler.umd.js:3342:27)
    at RecursiveAngularExpressionVisitor.visit (e:\GitRepo\angular2-seed\node_modules\codelyzer\angular\recursiveAngularExpressionVisitor.js:16:13)
    at InputMetadataWalker.Ng2Walker.visitNg2TemplateAST (e:\GitRepo\angular2-seed\node_modules\codelyzer\angular\ng2Walker.js:125:25)
    at InputMetadataWalker.Ng2Walker.visitNg2TemplateBoundElementPropertyAst (e:\GitRepo\angular2-seed\node_modules\codelyzer\angular\ng2Walker.js:138:14)
    at e:\GitRepo\angular2-seed\node_modules\codelyzer\angular\ng2Walker.js:145:60
    at Array.forEach (native)
    at InputMetadataWalker.Ng2Walker.visitNg2TemplateElement (e:\GitRepo\angular2-seed\node_modules\codelyzer\angular\ng2Walker.js:145:24)
    at InputMetadataWalker.Ng2Walker.visitNg2Template (e:\GitRepo\angular2-seed\node_modules\codelyzer\angular\ng2Walker.js:160:25)
```

my respective component look like : 

**home.component.html**
```
<p>
  Howdy! Here's a list of awesome computer scientists. Do you know any others? Add to the list yourself.
</p>

<form (submit)="addName()">
  <input [(ngModel)]="newName" name="newName" placeholder="Awesome Computer Scientist">
  <my-button [enabled]="isEnable">Add</my-button>
</form>

<ul>
  <li *ngFor="let name of names">{{name}}</li>
</ul>
```

**home.component.ts**
```
import { Component, OnInit } from '@angular/core';
import { NameListService } from '../shared/index';

/**
 * This class represents the lazy loaded HomeComponent.
 */
@Component({
  moduleId: module.id,
  selector: 'sd-home',
  templateUrl: 'home.component.html',
  styleUrls: ['home.component.css'],
})

export class HomeComponent implements OnInit {

  newName: string = '';
  errorMessage: string;
  names: any[] = [];
  isEnable:boolean = true;

  /**
   * Creates an instance of the HomeComponent with the injected
   * NameListService.
   *
   * @param {NameListService} nameListService - The injected NameListService.
   */
  constructor(public nameListService: NameListService) {}

  /**
   * Get the names OnInit
   */
  ngOnInit() {
    this.getNames();
  }

  /**
   * Handle the nameListService observable
   */
  getNames() {
    this.nameListService.get()
      .subscribe(
        names => this.names = names,
        error =>  this.errorMessage = <any>error
      );
  }

  /**
   * Pushes a new name onto the names array
   * @return {boolean} false to prevent default form submit behavior to refresh the page.
   */
  addName(): boolean {
    // TODO: implement nameListService.post
    this.names.push(this.newName);
    this.newName = '';
    return false;
  }

}
```

**my-button.component.ts**
```
import { Component, Input } from '@angular/core';

@Component({
    moduleId: module.id,
    selector: 'my-button',
    template: `<button type="submit" [disabled]="!enabled">Add</button>`
})
export class ButtonComponent {
   @Input() enabled:boolean;
}
```

With ref of pull request #101 I had modified function _visitNg2TemplateBoundElementPropertyAst_ of class **ng2Walker.ts**
```
protected visitNg2TemplateBoundElementPropertyAst(prop: BoundElementPropertyAst,
       context: ts.ClassDeclaration, templateStart: number) {
		const ast: any = (<e.ASTWithSource>prop.value).ast;
		ast.expression = (<any>prop.value).source;
		this.visitNg2TemplateAST(prop.value, context, templateStart + getExpressionDisplacement(prop));
    }
```
to 

```
protected visitNg2TemplateBoundElementPropertyAst(prop: BoundElementPropertyAst,
       context: ts.ClassDeclaration, templateStart: number) {
		const ast: any = (<e.ASTWithSource>prop.value).ast;
		if(!ast.expression) {
			ast.expression = (<any>prop.value).source;
		}
		
		this.visitNg2TemplateAST(prop.value, context, templateStart + getExpressionDisplacement(prop));
    }
```

and now this seems to be working for me. Request you to please verify this.

**Comment by mgechev** [comment]
Thanks for the comment and the snippet! The issue should be fixed but I haven't published it yet on npm.

**Comment by preslavsh** [comment]
Having same issue using branch fix-99
Snippet
`  import {Component } from '@angular/core';
@Component({
    selector: "sg-buy-form-component",
    template: \`
        <form>
        <input type="submit" [hidden]="hasOrdered" (click)="order(item.en_name);" class="btn-menu" value="Поръчай"/>
            <button [hidden]="!hasOrdered" class="bnt-red">Вече е
        поръчано
        </button>
        </form>\`
})
export class BuyFormComponent {
    public hasOrdered:boolean;
}`
StackTrace:
` TypeError: ast.expression.visit is not a function
  at SymbolAccessValidator.RecursiveAngularExpressionVisitor.visitPrefixNot (C:\Users\Presko\Desktop\codelyzer\codel
-fix-99\codelyzer\dist\src\angular\recursiveAngularExpressionVisitor.js:78:24)
  at PrefixNot.visit (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\@angular\compiler\bu
s\compiler.umd.js:3258:26)
  at ASTWithSource.visit (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\@angular\compile
ndles\compiler.umd.js:3314:27)
  at SymbolAccessValidator.RecursiveAngularExpressionVisitor.visit (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-
odelyzer\dist\src\angular\recursiveAngularExpressionVisitor.js:16:13)
  at Ng2Walker.visitNg2TemplateAST (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\dist\src\angular\ng
ker.js:125:25)
  at Ng2Walker.visitNg2TemplateBoundElementPropertyAst (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer
t\src\angular\ng2Walker.js:138:14)
  at C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\dist\src\angular\ng2Walker.js:145:60
  at Array.forEach (native)
  at Ng2Walker.visitNg2TemplateElement (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\dist\src\angula
2Walker.js:145:24)
  at Ng2Walker.visitNg2Template (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\dist\src\angular\ng2Wa
.js:160:25)
  at C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\dist\src\angular\ng2Walker.js:148:62
  at Array.forEach (native)
  at Ng2Walker.visitNg2TemplateElement (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\dist\src\angula
2Walker.js:148:26)
  at Ng2Walker.visitNg2Template (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\dist\src\angular\ng2Wa
.js:160:25)
  at C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\dist\src\angular\ng2Walker.js:176:30
  at Array.forEach (native)
  at Ng2Walker.visitNg2TemplateHelper (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\dist\src\angular
Walker.js:175:19)
  at Ng2Walker.visitClassDecorator (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\dist\src\angular\ng
ker.js:115:22)
  at Array.forEach (native)
  at Ng2Walker.visitClassDeclaration (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\dist\src\angular\
alker.js:72:40)
  at Ng2Walker.SyntaxWalker.visitNode (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\tsl
lib\language\walker\syntaxWalker.js:264:22)
  at C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\tslint\lib\language\walker\syntaxWalk
s:459:63
  at visitEachNode (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\typescript\lib\typescr
js:8251:30)
  at Object.forEachChild (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\typescript\lib\t
cript.js:8411:24)
  at Ng2Walker.SyntaxWalker.walkChildren (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\
nt\lib\language\walker\syntaxWalker.js:459:12)
  at Ng2Walker.SyntaxWalker.visitSourceFile (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modul
slint\lib\language\walker\syntaxWalker.js:190:14)
  at Ng2Walker.SyntaxWalker.visitNode (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\tsl
lib\language\walker\syntaxWalker.js:414:22)
  at Ng2Walker.SyntaxWalker.walk (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\tslint\l
anguage\walker\syntaxWalker.js:7:14)
  at Rule.AbstractRule.applyWithWalker (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\ts
\lib\language\rule\abstractRule.js:19:16)
  at Rule.apply (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\dist\src\noAccessMissingMemberRule.js:
21)
  at Linter.lint (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\tslint\lib\tslint.js:65:

  at lint (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\dist\test\testHelper.js:21:19)
  at Object.assertSuccess (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\dist\test\testHelper.js:61:2

  at Context.<anonymous> (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\dist\test\noAccessMissingMemb
le.spec.js:28:22)
  at callFn (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\mocha\lib\runnable.js:334:21)

  at Test.Runnable.run (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\mocha\lib\runnable
327:7)
  at Runner.runTest (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\mocha\lib\runner.js:4
0)
  at C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\mocha\lib\runner.js:535:12
  at next (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\mocha\lib\runner.js:349:14)
  at C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\mocha\lib\runner.js:359:7
  at next (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\mocha\lib\runner.js:285:14)
  at Immediate._onImmediate (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\mocha\lib\run
js:327:5)`

At the end turns out that hasOrderder in my case is string and cannot be visited.

**Comment by preslavsh** [comment]
Having same issue using branch fix-99
Snippet:
```
 import {Component } from '@angular/core';
 @Component({
    selector: "sg-buy-form-component",
    template: '
        <form>
        <input type="submit" [hidden]="hasOrdered" (click)="order(item.en_name);" class="btn-menu" value="Поръчай"/>
       <button [hidden]="!hasOrdered" class="bnt-red">Вече е поръчано</button>
        </form>'
})
export class BuyFormComponent {
    public hasOrdered:boolean;
}
```
StackTrace:
```
TypeError: ast.expression.visit is not a function
  at SymbolAccessValidator.RecursiveAngularExpressionVisitor.visitPrefixNot (C:\Users\Presko\Desktop\codelyzer\codel
-fix-99\codelyzer\dist\src\angular\recursiveAngularExpressionVisitor.js:78:24)
  at PrefixNot.visit (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\@angular\compiler\bu
s\compiler.umd.js:3258:26)
  at ASTWithSource.visit (C:\Users\Presko\Desktop\codelyzer\codelyzer-fix-99\codelyzer\node_modules\@angular\compile
ndles\compiler.umd.js:3314:27)
```

At the end turns out that hasOrderder in my case is string and cannot be visited.

**Comment by mgechev** [comment]
@preslavsh awesome catch! The issue you found is fixed now. I was overriding something which I wasn't supposed to.

**Comment by bonaparte89** [comment]
I ran into the error yesterday.. so first updated all deps. That wasn't working either. so cloned your seed-project again. Issue still around?


`C:\Users\user\Documents\WebProjects\Archiv\node_modules\codelyzer\angular\recursiveAngularExpressionVisitor.js:45
        var parts = ast.expression.split(/\{\{|\}\}/g).map(function (s) {
                                  ^
TypeError: Cannot read property 'split' of undefined
    at RecursiveAngularExpressionVisitor.visitInterpolation (C:\Users\user\Documents\WebProjects\Archiv\node_modules\codelyzer\angular\recursiveAngularExpressionVisitor.js:45:35)
    at Interpolation.visit (C:\Users\user\Documents\WebProjects\Archiv\node_modules\@angular\compiler\bundles\compiler.umd.js:3232:26)
    at ASTWithSource.visit (C:\Users\user\Documents\WebProjects\Archiv\node_modules\@angular\compiler\bundles\compiler.umd.js:3314:27)
    at RecursiveAngularExpressionVisitor.visit (C:\Users\user\Documents\WebProjects\Archiv\node_modules\codelyzer\angular\recursiveAngularExpressionVisitor.js:16:13)
    at InputMetadataWalker.Ng2Walker.visitNg2TemplateAST (C:\Users\user\Documents\WebProjects\Archiv\node_modules\codelyzer\angular\ng2Walker.js:125:25)
    at InputMetadataWalker.Ng2Walker.visitNg2TemplateBoundElementPropertyAst (C:\Users\user\Documents\WebProjects\Archiv\node_modules\codelyzer\angular\ng2Walker.js:136:14)
    at C:\Users\user\Documents\WebProjects\Archiv\node_modules\codelyzer\angular\ng2Walker.js:143:60
    at Array.forEach (native)
    at InputMetadataWalker.Ng2Walker.visitNg2TemplateElement (C:\Users\user\Documents\WebProjects\Archiv\node_modules\codelyzer\angular\ng2Walker.js:143:24)
    at InputMetadataWalker.Ng2Walker.visitNg2Template (C:\Users\user\Documents\WebProjects\Archiv\node_modules\codelyzer\angular\ng2Walker.js:158:25)`

**Comment by mgechev** [comment]
Yes, the fix is not on npm yet. You can clone and build the rules manually to verify that the problem doesn't occur anymore.
